/*
 * Copyright © 2026, Commonwealth Scientific and Industrial Research
 * Organisation (CSIRO) ABN 41 687 119 230.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * @author John Grimes
 */

/**
 * Sole producer of all SQL aliases generated by the tree walker.
 *
 * Routing every alias through here guarantees uniqueness across the whole
 * compile (the counter lives on Context.cteCounter and is shared by every
 * recursive walk call).
 */

import type { Context } from "./types.js";

/**
 * Generates a globally unique SQL alias for the current compilation.
 *
 * Increments the shared `ctx.cteCounter` (a mutable reference threaded
 * through every recursive walk call) and returns `"<prefix>_<n>"`.  Because
 * the counter is shared, aliases produced across different branches and depths
 * of the tree are guaranteed to be distinct within a single
 * `compileViewDefinition` call.
 * @param ctx - The current walker context; its `cteCounter.value` is
 *   incremented as a side effect.
 * @param prefix - A human-readable prefix that identifies the operator
 *   creating the alias (e.g. `"forEach"`, `"repeat"`, `"ua"`).
 * @returns A string of the form `"<prefix>_<n>"` that is unique within the
 *   current compilation.
 */
export function freshAlias(ctx: Context, prefix: string): string {
  const id = ctx.cteCounter.value++;
  return `${prefix}_${id}`;
}
