/**
 * Sole producer of all SQL aliases generated by the tree walker.
 *
 * Routing every alias through here guarantees uniqueness across the whole
 * compile (the counter lives on Context.cteCounter and is shared by every
 * recursive walk call).
 */

import type { Context } from "./types.js";

/**
 * Generates a globally unique SQL alias for the current compilation.
 *
 * Increments the shared `ctx.cteCounter` (a mutable reference threaded
 * through every recursive walk call) and returns `"<prefix>_<n>"`.  Because
 * the counter is shared, aliases produced across different branches and depths
 * of the tree are guaranteed to be distinct within a single
 * `compileViewDefinition` call.
 *
 * @param ctx - The current walker context; its `cteCounter.value` is
 *   incremented as a side effect.
 * @param prefix - A human-readable prefix that identifies the operator
 *   creating the alias (e.g. `"forEach"`, `"repeat"`, `"ua"`).
 * @returns A string of the form `"<prefix>_<n>"` that is unique within the
 *   current compilation.
 */
export function freshAlias(ctx: Context, prefix: string): string {
  const id = ctx.cteCounter.value++;
  return `${prefix}_${id}`;
}
